routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\DocumentReportController;
use App\Http\Controllers\FavouriteCourseController;
use App\Http\Controllers\SpecialityController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('welcome');

    Route::get('/courses', [CourseController::class, 'index'])
        ->name('courses.index');

    Route::get('/courses/{code}', [CourseController::class, 'show'])
        ->name('courses.show');

    Route::get('/courses/{code}/{document}', [DocumentController::class, 'show'])
        ->name('documents.show');

    Route::post('/add-favourite-course/{course}', [FavouriteCourseController::class, 'addFavouriteCourse'])
        ->name('add-favourite-course');

    Route::post('/remove-favourite-course/{course}', [FavouriteCourseController::class, 'removeFavouriteCourse'])
        ->name('remove-favourite-course');

    Route::post('/documents', [DocumentController::class, 'store'])
        ->name('documents.store');

    Route::post('/documents/edit', [DocumentController::class, 'edit'])
        ->name('documents.edit');

    Route::post('/delete-document', [DocumentController::class, 'delete'])
        ->name('documents.delete');

    Route::post('/download-selected-documents', [DocumentController::class, 'downloadSelectedDocuments'])
        ->name('download-selected-documents');

    Route::get('/my-documents', function () {
        return view('my-documents');
    })->name('my-documents');

    Route::get('/document-reports', [DocumentReportController::class, 'index'])
        ->name('document-reports.index');

    Route::post('/document-reports', [DocumentReportController::class, 'store'])
        ->name('document-reports.store');

    Route::patch('/document-reports/{id}', [DocumentReportController::class, 'update'])
        ->name('document-reports.update');

    Route::post('/update-dark-theme-preference', [UserController::class, 'updateDarkThemePreference'])
        ->name('update-dark-theme-preference');

    Route::get('/language/{locale}', function ($locale) {
        app()->setLocale($locale);
        session()->put('locale', $locale);

        UserController::updateLanguagePreference($locale);

        return redirect()->back();
    });

    Route::get('/legal-notices', function () {
        return view('legal-notices');
    })->name('legal-notices');

    Route::get('/privacy-policies', function () {
        return view('privacy-policies');
    })->name('privacy-policies');

    Route::get('/sitemap', function () {
        return view('sitemap');
    })->name('sitemap');
});
Route::prefix('/admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('document-reports', [DocumentReportController::class, 'index'])
        ->defaults('admin', true)
        ->name('document-reports.index');

    Route::get('/crawl-diplomes', [SpecialityController::class, 'manageSpecialities'])
        ->name('crawl-diplomes');

    Route::get('/crawl-uvs', [CourseController::class, 'manageUVs'])
        ->name('crawl-uvs');
});

require __DIR__.'/auth.php';

resources/views/legal-notices.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-4 flex flex-col gap-y-5 rounded-md bg-grey-200 dark:bg-grey-800 text-grey-950 dark:text-grey-50">
        <h1 class="uppercase font-extrabold text-2xl">{{ __('Legal notices') }}</h1>

        <h2 class="font-bold text-l">{{ __('Presentation of the service and stakeholders') }}</h2>
        <p>{{ __('This site is a service provided by the Service informatique de la Maison Des Étudiants (SiMDE), a committee of the BDE-UTC, intended for members of the Université de Technologie de Compiègne.') }}</p>
        <p>{{ __('The use by members of UTC complies with various applicable texts, including notably the computer charter of UTC.') }}</p>
        <p>{{ __('This site is developed and maintained by volunteers of SiMDE, as long as it is active.') }}</p>

        <h3 class="italic">BDE-UTC</h3>
        <dl>
            <dt>{{ __('Bureau des étudiants de l\'Université de Technologie de Compiègne') }}</dt>
            <dt>{{ __('Official acronym:') }} BDE-UTC</dt>
            <dt>{{ __('Siret:') }} 39777672500012</dt>
            <dt>{{ __('Registered office:') }}</dt>
                <dd>UTC - Centre Benjamin Franklin</dd>
                <dd>MDE</dd>
                <dd>BDE-UTC</dd>
                <dd>Rue Roger Couttolenc</dd>
                <dd>60200 Compiègne</dd>
            <dt>{{ __('Phone:') }} +33 3 44 23 44 23</dt>
        </dl>

        <h2 class="font-bold text-l">{{ __('Rights and obligations of users') }}</h2>
        <p>{{ __('By using the Shwet site, the user consents to their data being collected, stored, retained, and processed by SiMDE, and to documents published and their metadata being shared with other Shwet users.') }}</p>
        <p>{{ __('By using the Shwet site, the user agrees to:') }}
            <ul class="list-disc ml-6">
                <li>{{ __('not deposit documents on the platform of which they are not the legal owner or for which they do not have the required sharing rights.') }}</li>
                <li>{{ __('not deposit documents that are not related to activities carried out within the university framework during their course at UTC.') }}</li>
                <li>{{ __('not disclose false information.') }}</li>
                <li>{{ __('not attempt to compromise the integrity of the Shwet site in any way.') }}</li>
                <li>{{ __('contact the SiMDE at the address') }} <a href="mailto:simde@assos.utc.fr" class="text-purple-400 hover:underline">simde@assos.utc.fr</a> {{ __('upon discovery of any bug.') }}</li>
            </ul>
        </p>
    </div>
@endsection

resources/views/privacy-policies.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-4 flex flex-col gap-y-5 rounded-md bg-grey-200 dark:bg-grey-800 text-grey-950 dark:text-grey-50">
        <h1 class="uppercase font-extrabold text-2xl">{{ __('Privacy policy') }}</h1>
        <p>{{ __('Date of last update: 2024-10-31') }}</p>

        <p>{{ __('The text below aims to describe the policy for protecting data entered on the current site, Shwet.') }}</p>

        <h2 class="font-bold text-l">{{ __('Collected data') }}</h2>
        <p>{{ __('When you log in to Shwet, it is necessary to go through the SiMDE authentication portal (OAuth), which itself uses the UTC authentication portal (CAS). This authentication allows the Shwet site to collect and store the following user data:') }}</p>
        <ul class="list-disc ml-6">
            <li>{{ __('First and Last Name') }}</li>
            <li>{{ __('UTC Email Address (xxx@xxx.utc.fr)') }}</li>
        </ul>
        <p>{{ __('These details are required to associate a document deposited on Shwet with a specific user, the owner.') }}</p>
        <p>{{ __('Documents are files or links added by users and include metadata to be provided by the user. This metadata includes:') }}</p>
        <ul class="list-disc ml-6">
            <li>{{ __('UV: The UV code for which the user wishes to publish the document.') }}</li>
            <li>{{ __('Semester: The semester during which the document was created or obtained by the user.') }}</li>
            <li>{{ __('Type of Activity: The type of activity to which the document is related (e.g., exam, project, lab report, etc.).') }}</li>
            <li>{{ __('Document Type: Whether the document is a correction, a subject, or if the user created it themselves (Personal).') }}</li>
            <li>{{ __('Format: Whether the document is a file (PDF, Powerpoint, Word, etc.) or a link to an online document (Google Doc, etc.).') }}</li>
            <li>{{ __('Title: (OPTIONAL) Name given to the document if the user believes it necessary.') }}</li>
            <li>{{ __('License: CC0 (corresponding to the public domain) by default, indicates the document property and conditions of its usage. (Only applies to files, not links)') }}</li>
            <li>{{ __('Anonymous: If checked, no one will know who published the document. Otherwise, the owner\'s name will be displayed.') }}</li>
        </ul>
        <p>{{ __('Once on the site, the user preferences listed below are saved by the system:') }}</p>
        <ul class="list-disc ml-6">
            <li>{{ __('Theme (dark/light)') }}</li>
            <li>{{ __('Language') }}</li>
        </ul>

        <h2 class="font-bold text-l">{{ __('Data processing') }}</h2>
        <p>{{ __('All the data listed above is stored indefinitely to maintain the most comprehensive document database possible.') }}</p>
        <p>{{ __('All users have access to documents shared by each user on the platform. Users can request anonymous sharing of a document so that other users cannot know who owns it. However, administrators have the ability to view the identity of the user who published an anonymous document.') }}</p>

        <h3 class="italic">{{ __('Subcontractors under GDPR for this processing') }}</h3>
        <ul class="list-disc ml-6">
            <li>{{ __('Eliot DEWULF, president of SiMDE') }}</li>
            <li>{{ __('Quentin BOYER, vice-president of SiMDE') }}</li>
        </ul>

        <h3 class="italic">{{ __('SiMDE and administrators') }}</h3>
        <p>{{ __('All services are hosted on the SiMDE infrastructure, a committee of the BDE-UTC.') }}</p>
        <p>{{ __('Shwet administrators are volunteer members of SiMDE. To view the list of administrators, you can contact SiMDE at') }} <a href="mailto:simde@assos.utc.fr" class="text-purple-400 hover:underline">simde@assos.utc.fr</a></p>
        <p>{{ __('Shwet administrators have full access to the stored data.') }}</p>
        <p>{{ __('For maintenance and security purposes, administrators may consult and rectify the collected data.') }}</p>
        <p>{{ __('In accordance with the French Data Protection Act of January 6, 1978, and the General Data Protection Regulation (GDPR), you have the right to access, rectify, and delete information about yourself. To exercise these rights, you can contact SiMDE at') }} <a href="mailto:simde@assos.utc.fr" class="text-purple-400 hover:underline">simde@assos.utc.fr</a></p>

        <h2 class="font-bold text-l">{{ __('Cookies') }}</h2>
        <p>{{ __('This site does not use trackers. The only cookies used are for maintaining the current session.') }}</p>
    </div>
@endsection

resources/views/sitemap.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-4 flex flex-col gap-y-5 rounded-md bg-grey-200 dark:bg-grey-800 text-grey-950 dark:text-grey-50">
        <div>
            <h1 class="uppercase font-extrabold text-2xl">{{ __('Sitemap') }}</h1>
            <span class="text-sm">
                <i>{{ __("Last updated on June 23, 2024.") }}</i>
            </span>
        </div>
        <p>{{ __("Sitemap objective is to provide a structured list of all pages available on the site.") }}</p>

        <div>
            <ul class="list-disc list-inside">
                <li><x-link :href="route('welcome')">{{ __("Welcome page") }}</x-link></li>
                <li><x-link :href="route('courses.index')">{{ __("All courses") }}</x-link></li>
                <li>{{__("User pages")}}
                    <ul class="list-disc list-inside ms-5">
                        <li>
                            <x-link :href="route('my-documents')">{{ __("My documents") }}</x-link>
                        </li>
                        <li>
                            <x-link :href="route('document-reports.index')">{{ __("My reports") }}</x-link>
                        </li>
                    </ul>
                </li>
                @if(auth()->user()->isAdmin())
                    <li>{{__("Administrator pages")}}
                        <ul class="list-disc list-inside ms-5">
                            <li>
                                <x-link :href="route('admin.document-reports.index')">{{ __("Document reports") }}</x-link>
                            </li>
                        </ul>
                    </li>
                @endif
                <li>
                    <x-link :href="route('legal-notices')">{{ __("Legal notices") }}</x-link>
                </li>
                <li>
                    <x-link :href="route('privacy-policies')">{{ __("Privacy policy") }}</x-link>
                </li>
                <li>
                    <x-link :href="route('sitemap')">{{ __("Sitemap") }}</x-link>
                </li>
            </ul>
        </div>
    </div>
@endsection